### ISSUE TITLE
[Capacity] Ensure the stability of Capacity fees (Capacity tx fee)

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1015]
As the network that wants to ensure the stability of Capacity, the fee for a Capacity transaction is based on [something].

AC:
- Transaction cost should not change when generating new weights for Capacity transactions.
- The cost of a Capacity transaction stays the same regardless of the newly generated weights.
- The generated fee should not consider network congestion for Capacity.

**Comment by p5150j** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/1015?planning-poker) with Zenhub @enddynayn @johnmela @shannonwells

**Comment by p5150j** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/1015?planning-poker) with Zenhub @mattheworris

**Comment by shannonwells** [comment]
Instead of varying the chicken egg production (how many messages you could get per unit capacity) we are varying the cost per chicken (the token per capacity) as the way of handling congestion.  So what I am really saying is that the capacity cost needs to be related more to the message (the # of eggs per cake) itself than to weight  - though indirectly message cost can be related to a current weight calculation. Just as some cakes actually take more eggs than others.
