### ISSUE TITLE
[Private graph] race condition prevention 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1023]
### Definition
To remove race condition of stateful storage changes we are going to send the hash of current state in itemized and paginated requests.

### AC
- Modify Itemized extrinsic to get a hash value and compare it with the hash of current page and fail if the don't match
- Modify Paginated extrinsic to get the hash value (ignore comparing for now since we will need to read the page on chain) but this will allow us to add that later.
- Return hash with the storage rpc and add to page update event (validate against current hash)

### Question
- What hash function we should use and what should be the input param type be ? It can be a multihash type to support multiple hashes but ideally ti should only be 32 bytes hash algorithms. Please refer to @wesbiggs for that decision.

**Comment by wesbiggs** [comment]
To add a little color to this -- on the DSNP side the fact that it's a hash of a certain flavor will be opaque to an application (DSNP just thinks of it as an `etag`, like that header in HTTP). So I think the choice of hash function is up to Frequency. It does need to be computable on the client side, though, and it should vary when the page "chunk" (which is just a raw binary from Frequency's point of view) changes.

**Comment by JoeCap08055** [comment]
Does the hash really need to be computed on the client side? Maybe I'm misunderstanding how this will work, but I thought the hash would be something computed on the node when the page state is queried, representing the hash of the current state. That hash is then recycled by the client back to the node when a subsequent request is made. If the hash. If `client supplied hash <> current computed hash`, then the page state has been modified, operation is rejected and client must re-query current state in order to submit a change.

What am I missing?

**Comment by aramikm** [comment]
in practice if we expose the hash in retrieval the client might not need to calculate it themselves but I think there is a value in client side being able to calculate the hash independently and without being able to retrieve from node.

**Comment by wesbiggs** [comment]
@JoeCap08055 Good point, the requirement is that it be returned synchronously from a client/application point of view. If the node can do that, that's fine. We just don't wait to force an application to wait for a block to be published to learn the (probable) latest value.
