### ISSUE TITLE
[Handles] Spike: PRNG Simulations

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#1251]
Goals:

- [x] Identify `no_std` compatible rust crates for PRNG computation
- [x] Run simulations to generate random suffixes within a given range with varied msa ids (used as the seed)

Time box:
2 days

**Comment by rlaferla** [comment]
The `oorandom` crate is a good fit.  It's `no-std`, implements a PCG (permuted congruential generator), has over 17M downloads, and several projects using it including one that has 19M downloads.

https://crates.io/crates/oorandom

**Comment by rlaferla** [comment]
Alternatives:

https://crates.io/crates/nanorand (4.2M downloads, `no-std`, small footprint, used by several projects including one w/6M downloads)
https://crates.io/crates/rand (185M downloads, used by many large projects but only partial `no-std`, larger footprint)

**Comment by rlaferla** [comment]
@wilwade figured out a way to significantly improve the shuffled sequence design by using a PRNG seeded with the base user handle.  https://github.com/Liberty30/magic-rs/blob/main/src/main.rs

Therefore, we have made a decision to go with the shuffled sequence design but now with the PRNG seed instead of storing the shuffled vector of suffixes.
