### ISSUE TITLE
Benchmarking writes `pallet_collective` twice

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1267]
When running the benchmarking job it writes the `pallet_collective` file twice.

This might be a problem, but also could be due to the fact that we use the pallet_collective twice. (Council and Technical Committee)

Let's double check that this is not an issue.

https://github.com/LibertyDSNP/frequency/actions/runs/4485490323/jobs/7887093046

> Multiple benchmarks were written to the same file: "./scripts/../runtime/common/src/weights/pallet_collective.rs".

**Comment by JoeCap08055** [comment]
Hmm, interesting. It does indeed appear that's why--more specifically, it appears that it may be because the 2 instances of the pallet are configured with separate storages, so the benchmark runs against each storage--and appears to be generating a different number of reads/writes for the same extrinsic against the different storages.

Furthermore, it appears that the second set of weights (Technical Committee) completely overwrites the first set (Council) in the resulting file.

Looks like the issue is that our script specifies a filename for weight output instead of just a directory path. Tested locally, if I specify a directory instead of a filename, it generates 2 files: `pallet_collective_technical_committee.rs` and `pallet_collective_council.rs`. We should be able to solve this with some tweaks to the benchmark script & the `runtime/common` module definitions & `runtime/frequency` `use` import statements.
