### ISSUE TITLE
Clear metadata-mismatch label not working as expected in Verify PR Workflow

### ISSUE THREAD

**Issue by mattheworris** [LibertyDSNP/frequency#1582]
This PR is marked with `metadata-mismatch` when I don't expect that it should be, and there are no failed CI workflows.

https://github.com/LibertyDSNP/frequency/pull/1581/checks

**Comment by wilwade** [comment]
@mattheworris CI fails if it needs an updated spec version, but the label should stay if the metadata changes in any way. It is to notify the author and reviewers that something changed and if that is not expected, to check it.

**Comment by rlaferla** [comment]
I think the issue here is the interpretation of what the label means.  I think some of us thought the label meant that we forgot to increment the `spec_version` after changing the metadata.  The term "metadata mismatch" has a different connotation than a "metadata change".  If the `spec_version` has been incremented, it's an accounted for, intentional change.  I think we need to change the logic to display the corresponding label: "metadata-mismatch" vs. "metadata-change" @demisx @wilwade @mattheworris
