### ISSUE TITLE
RequiredSignature schemas should work on all extrinsics on stateful-pallet if called from owner

### ISSUE THREAD

**Issue by aramikm** [LibertyDSNP/frequency#1793]
Situation: If a user uses their on key for the transaction, a signature is still required.

Example: A user with tokens wants to remove some stateful storage data.

List of Extrinsics this might apply to and could need a version bump:
- `apply_item_actions_with_signature`
- `upsert_page_with_signature`
- `delete_page_with_signature`

Questions:
- Is this a desired change?
- What is the cost of the change?
- Should `delete_page_with_signature` be a free transaction if from the MSA owner?
- Is this a larger problem? (See Ideas C, D, E)

Ideas on how to make it happen:
- A. Allow for a `0x` signature value when it is from the owner, but do not change the signature.
- B. Create a separate set of extrinsics specifically for use with the owner as origin
- C. Create a new set of extrinsics to be used either by the owner origin, or via a wrapper extrinsics that reads the signature to make a new owner origin that is then passed to the "correct" extrinsic with the "correct" origin
- D. Create a new MSA owner origin in the MSA pallet and then route all sorts of stuff through a new extrinsic and all signature "required" extrinsics now go through that instead of via a separate signature. 
- E. Create a new proxy origin in a new pallet and then route all sorts of stuff through a new extrinsic and all signature "required" extrinsics now go through that instead of via a separate signature. It could also hold on to the signature registry and some things could require use of that.

**Comment by wilwade** [comment]
Notes from the 2023-12-21 Community Call

- Wrapping the call...
    - adds overhead
    - Reduces transparency and the ability check the transaction at the pre-dispatch stage
- Idea: Could we have an extension that did the proof checking?
    - Consuming from the extension is an unknown

**Comment by wesbiggs** [comment]
Thinking about the generalized problem of allowing users to submit transactions paid for by providers (Frequency community call agenda item for 2024-01-18), here are some ideas:

Consider a "Voucher" `V` issued to a user by a provider:

```
let v = { providerPublicKey, userPublicKey, expirationBlock, extrinsicId, userProviderNonce }
let s = signature over v using providerPrivateKey
let V = { v, s }
```

For every voucher-eligible operation we add a `_with_voucher` form of the relevant extrinsic; before proceeding with processing a transaction, each should check:
1. `origin == v.userPublicKey` (i.e. the user indicated in the voucher has signed the transaction)
2. `currentBlock <= v.expirationBlock`
3. `thisExtrinsicId == v.extrinsicId`
4. `v.nonce` has not been used previously (see below)
5. `signatureVerify(v.providerPublicKey, v, s)`

(Steps 2 and 3 are technically optional but help enforce "principle of least privilege" for the voucher.)

To avoid voucher reuse, chain state must contain a mapping `userPubKey => providerId => { nextNonce, rollingUsage }`, where `rollingUsage` is a bit string of length `MAX_OUTSTANDING_VOUCHERS` (a global value, either static or governance-managed). e.g. If `MAX_OUTSTANDING_VOUCHERS` = 8, then there can be up to 8 outstanding vouchers per user, per provider, taking up 8 bits of storage.

Each time a provider issues a voucher, they must submit extrinsic `increment_user_nonce(userPubKey, N)` which increments `nextNonce` for the user/provider pair by `N` and bit-shifts `rollingUsage` by `N` bits (i.e. `rollingUsage <<= N`).

Each time a user presents a voucher (i.e. submits a `_with_voucher` extrinsic), the chain checks that
4.1. `v.nonce < nextNonce` for the user/provider pair
4.2. `v.nonce >= nextNonce - MAX_OUTSTANDING_VOUCHERS`
4.3. The bit numbered `(nextNonce - v.nonce)` of `rollingUsage` == 0 (in other words, this voucher has not been used previously).

If that's all valid, the transaction is processed, and if successful, the checked bit in `rollingUsage` is set to 1.

(apologies in advance for any fencepost errors in the above)

Once all issued vouchers for a user/provider pair have been used, it should be possible to delete the chain state storage (i.e. allow for sparse data) as long as the provider is able to ensure that a previous nonce will not be reauthorized against the same public key. In most cases this could be accomplished by using an initial per-user nonce based on a timestamp or block number.

The assumption is that the user-submitted transaction would spend the voucher-signatory provider's Capacity; there is some risk that users could effectively collude by retaining vouchers and synchronizing their redemption in such a way as to effect a denial of service attack on the provider's Capacity allocation for the current Capacity Epoch. This feels like a problem that the provider can manage their own risk for, though.

There are lots of ways to vary this scheme. If we are unconcerned about the number of times a user can transact for a given voucher, things are much simpler, but I'm not sure a provider would be willing to write such a "blank check" that is bounded only by `expirationBlock`. We could also make it so that the same voucher is valid for a fixed number of uses (against some set of extrinsics) instead of just a single use, provided that the total of all outstanding voucher uses for the user/provider pair doesn't exceed `MAX_OUTSTANDING_VOUCHERS`.

**Comment by harry-evans** [comment]
For this part:The assumption is that the user-submitted transaction would spend the voucher-signatory provider's Capacity; there is some risk that users could effectively collude by retaining vouchers and synchronizing their redemption in such a way as to effect a denial of service attack on the provider's Capacity allocation for the current Capacity Epoch. This feels like a problem that the provider can manage their own risk for, though.You could also just charge capacity when they issue a voucher via increment_user_nonce, if it also indicated /signed the action the voucher was for. It is speculative (they are charged for capacity even if the voucher isn’t redeemed), but puts the spending timing back in the hands of the provider. On Jan 18, 2024, at 1:33 AM, Wes Biggs ***@***.***> wrote:﻿
Thinking about the generalized problem of allowing users to submit transactions paid for by providers (Frequency community call agenda item for 2024-01-18), here are some ideas:
Consider a "Voucher" V issued to a user by a provider:
let v = { providerPublicKey, userPublicKey, expirationBlock, extrinsicId, userProviderNonce }
let s = signature over v using providerPrivateKey
let V = { v, s }

For every voucher-eligible operation we add a _with_voucher form of the relevant extrinsic; before proceeding with processing a transaction, each should check:

origin == v.userPublicKey (i.e. the user indicated in the voucher has signed the transaction)
currentBlock <= v.expirationBlock
thisExtrinsicId == v.extrinsicId
v.nonce has not been used previously (see below)
signatureVerify(v.providerPublicKey, v, s)

(Steps 2 and 3 are technically optional but help enforce "principle of least privilege" for the voucher.)
To avoid voucher reuse, chain state must contain a mapping userPubKey => providerId => { nextNonce, rollingUsage }, where rollingUsage is a bit string of length MAX_OUTSTANDING_VOUCHERS (a global value, either static or governance-managed). e.g. If MAX_OUTSTANDING_VOUCHERS = 8, then there can be up to 8 outstanding vouchers per user, per provider, taking up 8 bits of storage.
Each time a provider issues a voucher, they must submit extrinsic increment_user_nonce(userPubKey, N) which increments nextNonce for the user/provider pair by N and bit-shifts rollingUsage by N bits (i.e. rollingUsage <<= N).
Each time a user presents a voucher (i.e. submits a _with_voucher extrinsic), the chain checks that
4.1. v.nonce < nextNonce for the user/provider pair
4.2. v.nonce >= nextNonce - MAX_OUTSTANDING_VOUCHERS
4.3. The bit numbered (nextNonce - v.nonce) of rollingUsage == 0 (in other words, this voucher has not been used previously).
If that's all valid, the transaction is processed, and if successful, the checked bit in rollingUsage is set to 1.
(apologies in advance for any fencepost errors in the above)
Once all issued vouchers for a user/provider pair have been used, it should be possible to delete the chain state storage (i.e. allow for sparse data) as long as the provider is able to ensure that a previous nonce will not be reauthorized against the same public key. In most cases this could be accomplished by using an initial per-user nonce based on a timestamp or block number.
The assumption is that the user-submitted transaction would spend the voucher-signatory provider's Capacity; there is some risk that users could effectively collude by retaining vouchers and synchronizing their redemption in such a way as to effect a denial of service attack on the provider's Capacity allocation for the current Capacity Epoch. This feels like a problem that the provider can manage their own risk for, though.
There are lots of ways to vary this scheme. If we are unconcerned about the number of times a user can transact for a given voucher, things are much simpler, but I'm not sure a provider would be willing to write such a "blank check" that is bounded only by expirationBlock. We could also make it so that the same voucher is valid for a fixed number of uses (against some set of extrinsics) instead of just a single use, provided that the total of all outstanding voucher uses for the user/provider pair doesn't exceed MAX_OUTSTANDING_VOUCHERS.

**Comment by wesbiggs** [comment]
> You could also just charge capacity when they issue a voucher via increment_user_nonce, if it also indicated /signed the action the voucher was for. It is speculative (they are charged for capacity even if the voucher isn’t redeemed), but puts the spending timing back in the hands of the provider.

Agreed.

**Comment by wilwade** [comment]
## Notes from Community Call 2024-01-18

Problem: Users may request signature required changes of a Provider, but the Provider might fail to do the transaction the user requested of them. (Delegation would is still used alone for non-signature required actions)

Possible solution: Can/How could we have users submit MSA related management transactions to the chain instead of the providers?

### Issues with Provider Transacting
- Transparency: The action may not occur, and the user is unaware that it didn't
    - Assumption: The Provider wishes to do the action (AddProvider)
    - Reality: Provider may make mistakes


### Issues with User Transacting using Provider Capacity
- Provider needs to know how much capacity they are using and when
- Provider needs to know that they WANT to do a transaction
- Replay attacks

### If we did Transaction Vouchers/Tickets
- When does the user get those from the Provider?



### Question: Can we narrow the scope of the problem? ie, a bootstrapping issue (creating a new MSA & granting delegations to that provider).
1. Revoking delegations is already free, as is removing a key from an MSA (I think?)
2. Really the main use case for paid transactions is creating an MSA, and granting delegations (handle claim also, but that could be incorporated into MSA creation)
3. Any other transactions after you've onboarded with a provider can be done via that provider

#### Answer: Maybe?
- DSNP Private Graph key creation/rotation might have the same issue
- Handle creation might also have the same issue (I wanted handle `x`, but it didn't go to the chain, so now cannot get handle `x`)
- `AddProvider` Delegation is not a problem as that really is the responsibility of the Provider

Helpful starting point [sequence diagram](https://mermaid.live/edit#pako:eNqNVNtO20AQ_ZXRPlSt6oSEOCSxKpAFREUqKCLQSFVeFnuSbLF33b0AKeLfO2vHuRGk5snZOTNz5szllSUqRRYxg38cygQvBJ9rnk8l0I8nVmmIgRu4N6irx4JrKxJRcGlh5E0jrZ5Eesg88eY4SZSjP-cauRVKwv0VHMGEZxna9y5D7zLUFZvlVFaIuHF6OorgpzDCwlhYrJ5H9DyJ4NajjYUfai7k0VjMpSsqwIQAX4cRnC8weYQZFXM9jk0A37lMM6QPtEmz2azAwwahGxRvD3OBGc5L6nsOPnocwZjsiV3XSUnKUhFu8LkC3ij6p56QtAw8m8pcOwwz9QzCQKLyIsOX5rcHfXRa1gJKZkvwYgiNBn47KtIusCoUYmcX4Kvl1mncCDVZU9rnUcoRbwQbKp3XeQn3eVMp8KKgtvKs1qGu_EudZ6WVDwEX3PJNBp-_ZmUiiNO0npAAFjvB3qtDvnFmUZO3eMK6_aqwcF0VTzo9ICxQ41llW9c12tQ14sscSdk7kTzWQ1bNy4r1IQDKdHdoxu4hp3G701wa2gTf_4OEtwAw5CKjss_KHl7JmVfH0eqAmsGssgFJADT91PTSYpXfs4DabPXyg4ncTjF2SYLG1NqsFP94JCbV7txiSkNEQ0H56n7AsyD8IafRzuLYBbdbawCfynMAly_CWLNN1e8oz0RKU5duAsUlvTmmcCWnsia-p-K505pa8p-cNwO2y7cWqtx1vypufbfeM_mI9-EuUzAaERawHHXORUpH89Ujp4zy5DhlEX2mOOMus1M2lW8EdYUPeZkKuqMsmvHMYMC4s2q8lAmLrHZYg1aHd42ia8iiV_bCoka_1wyPw1a312qd9DvdQRiwJT2HvV6zH3bD_qDbag-6nfZbwP4qRSHazf5gEHba_V4nHBy3B52TMt6v0uiTvv0DLq7kUQ)

## Outcomes
- Please add notes, diagrams, and flow charts of how you think this could be solved (either by figuring out ways around the issues of user submission or alternatives entirely)
- Look for solutions for specific transactions instead of generally for all signed transactions

**Comment by aramikm** [comment]
One alternative might be to generate a unique VoucherId per voucher request (using block_number, extrinsic_index) and store it in a map as
`VoucherId` -> `userAccountId`
which allows `userAccountId` to consume that voucherId. 
After consuming (applying extrinsic) we must remove the voucherId, so it would not suffer from replay attacks but the issue is with leftover vouchers which would need cleanup periodically. It would require another service (indexer) for offchain detection and on-chain cleanup call.

**Comment by wilwade** [comment]
## Voucher related questions:
(@wesbiggs / @harry-evans, Do you imagine...)
- Would a voucher be for a specific action or an amount of Capacity? (as even the same action can take different amounts of capacity depending on the data)
- What is required from the end user for a voucher to be issued?
    - @wesbiggs you have listed just`userPublicKey` and `extrinsicId`
    - If a user has those, the user can submit all the 
- Does the voucher need to be submitted to chain?
    - There is a signature registry system that could be used to ensure the provider signatures are not reused in the way that user signatures are currently.

## Communication Issues

A large advantage of the existing system is that the flow does not require any secondary interactions. The user passes off data to the provider and the provider to the chain. Done. (User here meaning the wallet+ui the user is using)

Other systems all appear to require a second interaction with the user:

- Current: User -> Provider -> Chain
- Desired (but might not be possible): Provider -> User -> Chain
- Voucher: User -> Provider -> Chain -> User -> Chain
- Signature System: User -> Provider -> User -> Chain
- Mempool Multisig System: (User -> Mempool, Provider -> Mempool) -> Chain

## Mempool Multisig System

What about being optimistic and using the mempool instead?

This is a wild idea, but could we use the mempool to collect the two sides of the "transaction" together?

- Provider submits an authorization to use capacity to the mempool
- Mempool sits on that transaction until there is a completing transaction (or it expires)
- Provider sends user [something] that must be included in the user's transaction
- User submits transaction with the [something] that is then paired with the provider's transaction in the mempool
- The mempool then validates the two transactions _together_ as "one" and the transaction is processed.

**Comment by JoeCap08055** [comment]
Note: perhaps we should create a separate issue; conversation thread in the comments seems to be somewhat diverging from the intent of the original issue as described)

Regarding specifically `SignatureRequired` schemas and the ability (or lack thereof) of a token-holding user to invoke extrinsics in the `stateful-storage` pallet, it seems to me that the original problem is slightly mis-stated:

* A token-holding user _should_ be able to call the non-signature versions of `apply_item_actions`, `upsert_page` and `delete_page`; however, for `SignatureRequired` schemas they are required to use the `_with_signature` variants, which is an unnecessary burden on the user

It seems to me that the solution to this specific problem is simple:
1. If a token-holding user chooses to use the `_with_signature` version of the extrinsics, they must sign their own payload and submit it.
2. If a user invokes the non-signature version of one of the extrinsics:
    a. If the user === msa_owner, consider the payload signed as it has been invoked signed with the user/owner's control key
    b. If the user !== msa_owner (delegate), consider the payload unsigned for purposes of checking against a `SignatureRequired` schema; delegates must use the `_with_signature` version of the extrinsic to submit.
    
    
Am I misunderstanding the issue? Seems fairly simple; I feel like I must be missing something. Vouchers are an interesting topic, but I don't see their relevance to this specific issue. The ability of a user to initiate a transaction that a provider will pay for should be a separate issue.

**Comment by wilwade** [comment]
Moved the secondary conversion to a separate issue: https://github.com/LibertyDSNP/frequency/issues/1849
