### ISSUE TITLE
Data for Crowdloan Script

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#334]
In progress by @jeetumaker

Once the crowdloan is complete, we need a list of what the calculated value is that should be minted to the supporters.

The output of this will be input into #333 so that the values can be set with sudo.

## Acceptance Criteria
- JSON (see example below)
- List should be published into a public github repo

### Example Output

```json
[
    { "address": "5CA5x7GiXAvZuHPTx49TFCB8YJCWrrkYg6sZ1fK6BZuxwfHH", "amount": "123456789" },
    { "address": "5DhbAAAGN8NoACsCS9VF8YWscH5niruxp64zhm47BhnxiyUN", "amount": "987654321" },
]
```

**Comment by jeetumaker** [comment]
@wilwade , should every address in the output file be listed once with total amount for that address or would you like to see address & amount based on every contribution made on the chain.  Since rewards % could be different for every contribution from the same address, I'm not sure if this file should have breakdowns or simply total rewards.  Please advise

**Comment by wilwade** [comment]
@jeetumaker Hmm... Let's do totals. We'll make sure enough of the other data is public to be transparent about the calculations.
