### ISSUE TITLE
Check delegations at a given block number without a full node

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#430]
As a content reader wanting to validate an off-chain claim of delegation at a historical point in time, I want to be able to know that a provider_msa_id was delegated to by one or more delegator_msa_ids at a given block number. I don't want to have to have an archive node to do this.

## Arch Notes
- check_delegations is an existing RPC interface, but it only does current delegation testing, not historical
- "No Archive Node" means that we have to do the lookup and then check the block number and not rely on `at` for a historical state check
- It will require some rework of the functions it calls
- Be careful when working with the functions that are called on-chain vs ones only called off-chain

## Acceptance Criteria
- [x] I should be able to call a custom RPC with a block_number, provider_msa_id, and list of delegator_msa_ids and be able to know which delegations were valid at that point in time.
- [x] I should still be able to call the same or another RPC with the current block number assumed
- [x] I should NOT be able to request a block number greater than the current block number

**Comment by mehtaishita** [comment]
what does _'I don't want to have an archive node to do this'_ mean?
does 'current delegation testing' mean only on-chain validation?

**Comment by aramikm** [comment]
One way to do this might be by enabling offchain worker very `N` number of blocks and update offchain db with delegation data but there are a number of concerns

1. is it possible to modify this data since it is off-chain and if somebody can do this then they can have access on some data that they should not have
2. Is data going to be consistent across different nodes?
3. what is the cost for this process?

**Comment by aramikm** [comment]
Other obvious way might be to keep delegations on-chain and do not remove them after they are expired
