### ISSUE TITLE
Add Frequency Logo to Polkadot Vault (Parity Signer)

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#601]
As a user of Polkadot Vault (formerly Parity Signer) I want to have the Frequency and Frequency Rococo Logos show up.

See https://github.com/paritytech/parity-signer/issues/1440 for details on how to do this.

- [ ] Frequency Logo in iOS
- [ ] Frequency Logo in Android

Removed Frequency Rococo as the updated Polkadot Vault doesn't have the display issue that Parity Signer had.
- ~Frequency Rococo Logo in iOS~
- ~Frequency Rococo Logo in Android~

**Comment by rlaferla** [comment]
Logo needs to be b&w for the font.

**Comment by rlaferla** [comment]
https://developer.mozilla.org/en-US/docs/Web/Guide/WOFF

**Comment by rlaferla** [comment]
Seems to be already in Parity Vault (iOS)
![Image from iOS](https://github.com/LibertyDSNP/frequency/assets/1135694/8fcfb32a-6458-4ff8-a5db-8752946b3469)

**Comment by p5150j** [comment]
I think we want the updated logo

**Comment by rlaferla** [comment]
Parity replied with:

The logic for Android can be found in the file io/parity/signer/components/networkicon/NetworkIcon.kt, specifically at line 94. You will find all the known icons there. The preferred format for these icons is Android vector drawable, which can be created using Android Studio from an SVG file. However, please ensure that the SVG file does not contain a PNG resource blob, as is the case with two icons in the code due to their more complex SVG structure. The icons have dimensions of 56x56 pixels. It's important to note that the string used for the icons is taken from the network logo field, not the network name. Please keep this in mind, as there may be differences for certain networks.

**Comment by rlaferla** [comment]
For iOS, we need to add a `Frequency.imageset` folder to `ios/PolkadotVault/Resources/ChainIcons.xcassets` in the Parity Signer repository.

The `Frequency.imageset` folder should contain:

`Frequency.svg`
A 56x56 svg.

`Contents.json`
{
  "images" : [
    {
      "filename" : "Frequency.svg",
      "idiom" : "universal"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}

**Comment by rlaferla** [comment]
https://github.com/paritytech/parity-signer/pull/1845

**Comment by rlaferla** [comment]
https://github.com/paritytech/parity-signer/pull/1845/files/bffce6bb5b44dc43153d034efd46929965c8e893..67ec861eb661b06919d4f46d8415ccaa4dd1b812

**Comment by rlaferla** [comment]
![image](https://github.com/LibertyDSNP/frequency/assets/1135694/d325aae6-fc6f-4057-9ddf-b40c08f18a90)

**Comment by rlaferla** [comment]
![image](https://github.com/LibertyDSNP/frequency/assets/1135694/d43dee76-e76a-4d76-99e2-48d6937b1797)
