### ISSUE TITLE
Assign values to Error enums to avoid ordering issues

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/frequency#622]
As enums have an underlying value that change according the order in the declaration, we can prevent these issues by assigning a value to each.

For example, _Substrate_ does this:

```
pub enum ErrorCode {
    /// Returned when BEEFY RPC endpoint is not ready.
    NotReady = 1,
    /// Returned on BEEFY RPC background task failure.
    TaskFailure = 2,
}
```

**Comment by rlaferla** [comment]
**Implementation of the types and their (de-)serialisation via SCALE codec.**
https://docs.substrate.io/reference/scale-codec/
https://www.npmjs.com/package/@polkadot/types/v/1.2.0-beta.23

**Comment by shannonwells** [comment]
also blocked by #645

**Comment by wilwade** [comment]
After many questions we figured out that we do not yet need to do this.

Why not?
- Metadata does contain the enum name connection to the enum. So people pulling the metadata don't care if we switched things around

Why maybe eventually?
- People who are not relying on fetching the metadata and processing it at runtime would potentially misinterpret the data.

Current:
- After release we should try hard not to re-order so that the changes to the metadata are limited to try to prevent churn, but we will not be offering any guarantees to maintain the encoding enums.

Future:
- Perhaps if we remove an older enum value, we would want to number the remaining ones to prevent churn, but still no guarantees
