### ISSUE TITLE
Schema permissions can only be inserted/updated with mutual agreement between provider and delegator.

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#876]
Schema permissions can only be inserted/updated (upsert) with mutual agreement between provider and delegator.  Granting, revoking/removing of schemas will be removed.

For example, a user signs up with a provider.  At a later time, provider deploys a new feature.  The user is prompted whether they want to use this new feature.  When they agree, the schema permissions are upserted to reflect it.

## Acceptance Criteria
- Permissions should not be able to be added without permission of both the delegator and the provider.
- Permissions changes are *not* required to be additive only
- Provider should resubmit to `grant_delegation` the new delegation (_aka put_) to completely replace the prior delegation
- grant_schema_permissions should be removed (_security issue_)

**Comment by rlaferla** [comment]
`grant_schema_permissions()` should be deprecated (rather than simply removed), correct?

**Comment by rlaferla** [comment]
"The issue (with `grant_schema_permissions()`) is that it doesn't require signatures from both the delegator and the provider. So the delegator can force the provider into a relationship that it did not agree to." @wilwade

**Comment by shannonwells** [comment]
Here's my super-high-level user story:
Because sometimes I change my mind about what messages a Provider may post on my behalf, I want to be able to re-authorize a schema grant for a Provider that was previously revoked, so they can resume posting them from a specific point in time.
comments after discussion with @rlaferla  about how this would work:
(@p5150j your input?)

From the Provider standpoint:
So that I can provide premium services (in the form of types of messages I will submit) to certain users, I would like to be able to add/remove schema grants as needed for a given user, who may upgrade or downgrade their account services.

From ethical considerations standpoint:
If I as a user can _never_ re-authorize a Provider to post messages on my behalf, this dramatically increases switching cost, because I will have to think really hard about de-authorizing a Provider.  This makes it much less likely for me to de-authorize and therefore it coercively reduces my freedom to choose Providers.

I think that these are important stories to try to fulfill and it makes me ask what fulfilling that looks like on chain.

**Comment by wilwade** [comment]
This scenario should work, perhaps we need a test for it:

1. User A delegates to Provider X with Schema Ids 1, 2, and 3
2. User A revokes all delegation to Provider X at Block Number 100
3. User A delegates to Provider X again with Schema Ids 2, 3, and 4

Final State:
- User A has a Delegation with Provider X
- Schema 2, 3, and 4 are granted
- Schema 1 is marked as revoked at Block Number 100

**Comment by wilwade** [comment]
Acceptance Criteria Missed: `grant_schema_permissions` was not removed.
