### ISSUE TITLE
[BUG] Metadata autosign workflow failed

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#881]
Metadata portal one: Metadata autosign workflow failed to produce a autosign pr

**Comment by rlaferla** [comment]
This was due to a stale branch.  We will analyze the autosigner workflow to see how we could prevent these stale branches and update the documentation accordingly.

We have already:

- Deleted the stale branch
- Added diagnostic logging
- Improved the documentation (NOTES.md)

We will re-run the autosigner workflow once the blocking issue of incorrect metadata has been fixed for the 1.0.x release.

**Comment by p5150j** [comment]
seems to be working, closing
