### ISSUE TITLE
Polkadot v0.9.36 upgrade

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#919]
This is a high priority release and you must upgrade as as soon as possible.

https://github.com/paritytech/polkadot/releases/tag/v0.9.36

**Comment by rlaferla** [comment]
I've made some significant progress with this upgrade but there are some issues:

1.  Parity has deprecated implicit call indices.  Therefore, we need to add [pallet:call_index(xx)] decorations to explicitly mark all pallet calls.  We need to understand the implications of this and apply them.

2.  The node service (which I am not quite familiar with) apparently was based on an early template in _Cumulus_.  The _Cumulus_ template code for it was using a temporary hack because _Substrate_ lacked some functionality.  Now, with this upgrade, they are no longer using `SharedImportQueue` in the client service.  Given the history, it would be helpful if we had architectural documentation that described what this service does (for example, sets up various queues) and what customizations we made to it for _Frequency_.  

```
    Checking frequency-service v0.0.0 (/src/frequency/node/service)
error[E0433]: failed to resolve: could not find `SharedImportQueue` in `cumulus_client_service`
   --> node/service/src/service.rs:308:45
    |
308 |     let import_queue = cumulus_client_service::SharedImportQueue::new(params.import_queue);
    |                                                ^^^^^^^^^^^^^^^^^ could not find `SharedImportQueue` in `cumulus_client_service`
```

At this point, we could patch the code that we have but it probably is better that we use their latest code as a template and modify it to fit our needs.  This will allow us to not only get the upgrade working but make it easier to sync with their base - especially for security and functionality updates.

**Comment by rlaferla** [comment]
https://paritytech.github.io/substrate/master/frame_support/attr.pallet.html#palletcall_indexidx

**Comment by rlaferla** [comment]
We are holding off on the 0.9.36 upgrade and are instead upgrading to 0.9.33 for now.

**Comment by wilwade** [comment]
Upgrade to 0.9.33 complete, this one might now be possible. Reopening for verification.
