### ISSUE TITLE
Provider Reserved MSA Id

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#945]
As a provider I would like to reserve a batch MSA Id as I am migrating web2 users in my platform to frequency so that I do not have to manage hybrid identifiers. 

- Need to give the provider a way to request this batch
- Need a way to limit the batch requests to a max batch size (100 million) 
- Once voted and approved referenda 2nd function create_sponsored_account_with_delegation_with_reserved_id that has 2 checks; one: checks the provider is using 1 of its reserved ids two: the msa id isnt already used

Business Goal tl;dr: Make it so that Web 2.0 platforms migrating to Frequency do not have to support a hybrid user identifier model. Instead they can "immediately" allocate all of their users an MSA Id at "once"

More Details on options and such: https://docs.google.com/document/d/1fzKKRvttODRjo2eGungFxAdXxVULgDzfdjA2hXZsZ_E/edit?usp=sharing

Basic Initial Issue/Design Doc outline:

- New way for a provider to reserve an MSA Id (no delegation permissions or messages allowed, it is just a placeholder)
- New way for a provider to allocate a reserved MSA Id to a new sponsored account
- Way to find out if an MSA Id is reserved and by which Provider MSA if it is (history once a "full" MSA we don't care who originally reserved it)

Open Questions:

- How to limit the number of reserved MSA Ids so someone cannot just reserve all of them Answer: Through governance 
- Is this a capacity transaction or not? (`create_sponsored_account_with_delegation` will be one) Answer: YES.

**Comment by rlaferla** [comment]
My initial concerns per our earlier discussion is that even though we have governance, we should have a safety valve on it.  a  Because early on, we won't have many users that will vote on it and b. Errors/bugs/mistakes happen and limiting the exposure/impact is prudent. Secondly, do we really want to have a massive number of individual transactions (say 10 million) hit the chain instead of batches?

**Comment by rlaferla** [comment]
What is the cost/fee to reserve MSA ids?  It probably should correlate to the number of reserved ids requested.

**Comment by rlaferla** [comment]
Notes...  MSA id has a maximum range of `18446744073709551615` values.  MSA functions that may be utilized/impacted in the implementation include:  `get_current_msa_identifier_maximum()`, `get_next_msa_id()`, `set_msa_identifier()`

**Comment by rlaferla** [comment]
What exactly does `create_sponsored_msa()` do?   It is mentioned above with no definition.

**Comment by rlaferla** [comment]
Need further written clarification on `create_sponsored_account_with_delegation_with_reserved_id()`

**Comment by rlaferla** [comment]
We will need a constant or variable for `max_reserved_ids_per_request`.  Do we want this value to be changed via governance?

**Comment by rlaferla** [comment]
A provider reserves batch of MSA ids by governance proposal.  The `number_of_ids` to be limited by `max_reserved_ids_per_request`

`proposeMsaReservation(provider_id: MessageSourceId, number_of_ids:u32)`

**Comment by rlaferla** [comment]
What information is stored once the proposal is approved?   Provider id, range of MSA ids (inclusive range), anything else?

**Comment by rlaferla** [comment]
As per earlier discussion with @wilwade, we will allow gaps in the MSA ids and not try to fill them.

**Comment by rlaferla** [comment]
Is the initial implementation dependent upon Capacity?  @wilwade Please clarify.

**Comment by rlaferla** [comment]
What constitutes approval of the proposal?  Simple majority (>50%)?

**Comment by wilwade** [comment]
> What is the cost/fee to reserve MSA ids? It probably should correlate to the number of reserved ids requested.

For this version, we do not need an additional fee over the standard weight. The proposal alone requires a lock of 100 FRQCY and cancellation of that proposal by 2/3 of the council results in a it being lost. (The lock is removed once the proposal is completed if it is not cancelled)

> MSA functions that may be utilized/impacted in the implementation include: get_current_msa_identifier_maximum(), get_next_msa_id(), set_msa_identifier()

`retire_msa` is also impacted. I believe to correctly prevent re-creation of a retired msa by a provider, we will need to retain the msa with `0` keys attached. Effectively mutating `PublicKeyCountForMsaId` to store the 0 instead of going to None. We will want to make sure this doesn't have any secondary effects (a quick look did not show any). Also, as retiring is expected to be rare, the minor additional storage is worthwhile.

> create_sponsored_msa

This is just referring to `create_sponsored_account_with_delegation`. I'll update.

> create_sponsored_account_with_delegation_with_reserved_id

Correct. That signature is correct as far as I can tell. The important bit that the signature captures is that it takes the same data as `create_sponsored_account_with_delegation`. That said, feel free to try to find a way to shorten it.

> We may need a constant or variable for max_reserved_ids_per_request. Do we want this value to be changed via governance?

This can just be a constant. No need to be additionally changeable via direct governance action.

> `proposeMsaReservation`

Two notes here:

1. Yes it should include the number of requested ids.
2. It is not a proposal. As this is a referendum, it is just the action itself. So a name like: `reserve_msa_ids` would be more appropriate. It is merely limited to the origin of Root.

> What information is stored once the proposal is approved? Provider id, range of MSA ids (inclusive range), anything else?

We should allow for multiple ranges (although don't really expect any).

> we will allow gaps in the MSA ids and not try to fill them.

✅ 

> Is the initial implementation dependent upon Capacity?

No. This is merely a note that `create_sponsored_account_with_delegation_with_reserved_id` is to be added to the list of capacity possible transactions


> Is it a Council or Public referenda? What constitutes approval of the proposal? Simple majority (>50%) or perhaps a super majority (>66%)?

A standard public referenda. I believe those are majority (after applying the conviction voting).

**Comment by rlaferla** [comment]
It's my understanding that it's either a council or public proposal which then becomes a referendum:

> Referenda can be started in one of several ways:
> 
> Publicly submitted proposals (28 days);
> Proposals submitted by the council, either through a majority or unanimously (28 days);
> Proposals submitted as part of the enactment of a prior referendum;
> Emergency proposals submitted by the Technical Committee and approved by the Council (fast tracked).

Therefore, are you thinking of a fast-tracked proposal?

**Comment by wilwade** [comment]
@rlaferla Correct a public proposal that would turn into a referenda is what I mean.

We are set to 7 day period for proposals and referenda (https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F1.rpc.frequency.xyz#/democracy)

**Comment by rlaferla** [comment]
So, I then can use proposeMsaReservation(), correct?

**Comment by rlaferla** [comment]
For reserving MSAs, if the proposor is specifying the number of MSA ids, we should set a minimum number.   What should it be?

**Comment by wilwade** [comment]
@rlaferla 
> minimum number

1 I guess? I don't see why we'd need to enforce a minimum over 1, but open to thoughts.

> `proposeMsaReservation`

I think we should avoid `propose` because we use that elsewhere to create a proposal in a collection. In this case you create the proposal by calling the democracy pallet directly. Perhaps `msa_reservation_via_governance`? but that implies that regular users cannot use it.

With most of the referenda actions, the action is the direct thing you want to do. So I think `provider_reserve_msa_ids` or something like that might be best. Open to ideas.

**Comment by rlaferla** [comment]
What is the value of reserving a single MSA id when you can simple get one?   I was thinking that this reservation system's purpose was to fill the needs of large providers.  While there isn't a magic number, perhaps 1,000 minimum?  I'm fine with setting it to lower values.  I just am questioning the business case.

**Comment by rlaferla** [comment]
We currently use the _via_governance for the action taken when a proposal approved, so I think it should something different.  As for creating the proposal, we currently use the extrinsics `propose_to_be_provider()` and `propose_to_create_schema()` so I don't see what we shouldn't use something like `propose_msa_reservation_for_provider()`.  I argue that it would be consistent to use this naming.  The internal propose methods are a different matter but those are on a `CouncilProposalProvider` whereas this would be a `PublicProposalProvider` (or similar.)

**Comment by rlaferla** [comment]
As per verbal discussion w/ @wilwade, the idea is to have the provider use the `Polkadot UI `to create a _preimage_, etc...

**Comment by rlaferla** [comment]
The storage of MSA id ranges will need to be flushed out if/when we address this issue.

**Comment by rlaferla** [comment]
This issue has been reprioritized.

**Comment by wilwade** [comment]
We have chosen for now to not proceed with this idea for the time being.
